#!/usr/bin/env python3
"""Build the Databricks API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Cluster Policies': 'Cluster Pol.',
    'Instance Pools': 'Inst. Pools',
    'Statement Execution': 'Stmt Exec',
    'Vector Search Idx': 'VS Indexes',
    'Vector Search Endpts': 'VS Endpoints',
    'External Locations': 'External Loc',
    'Storage Credentials': 'Storage Creds',
    'Serving Endpoints': 'Serving Endpts',
    'Token Mgmt': 'Token Mgmt',
    'Current User': 'Current User',
}

LINES = [
    {
        "name": 'Workspace & Compute',
        "color": '#FF3621',
        "stations": [
        ('Databricks', (270, 195)),
        ('Workspace', (430, 175)),
        ('Clusters', (590, 165)),
        ('Cluster Policies', (760, 175)),
        ('Instance Pools', (960, 200)),
        ],
    },
    {
        "name": 'Jobs & Pipelines',
        "color": '#0E9D6E',
        "stations": [
        ('Jobs', (270, 320)),
        ('Pipelines', (440, 295)),
        ('Repos', (610, 295)),
        ('Git Creds', (790, 295)),
        ('Libraries', (960, 320)),
        ],
    },
    {
        "name": 'SQL & Tables',
        "color": '#1E5BD0',
        "stations": [
        ('SQL Warehouses', (270, 425)),
        ('Statement Execution', (470, 405)),
        ('Queries', (660, 405)),
        ('Alerts', (820, 405)),
        ('Tables', (980, 425)),
        ],
    },
    {
        "name": 'Unity Catalog',
        "color": '#7B3FE4',
        "stations": [
        ('Catalogs', (270, 540)),
        ('Schemas', (430, 515)),
        ('Volumes', (590, 515)),
        ('Functions', (760, 515)),
        ('Grants', (920, 540)),
        ],
    },
    {
        "name": 'ML & Vector Search',
        "color": '#E68B1F',
        "closed": True,
        "stations": [
        ('Serving Endpoints', (820, 590)),
        ('Vector Search Idx', (910, 660)),
        ('Vector Search Endpts', (820, 730)),
        ('Model Versions', (730, 660)),
        ],
    },
    {
        "name": 'Storage & Data Sharing',
        "color": '#C5318B',
        "stations": [
        ('External Locations', (270, 670)),
        ('Storage Credentials', (470, 645)),
        ('Metastores', (640, 645)),
        ('Connections', (790, 670)),
        ],
    },
    {
        "name": 'Identity & Admin',
        "color": '#5A6275',
        "stations": [
        ('Tokens', (270, 800)),
        ('Token Mgmt', (390, 800)),
        ('Permissions', (510, 800)),
        ('Groups', (610, 800)),
        ('Current User', (700, 800)),
        ('Apps', (790, 800)),
        ('Files', (880, 800)),
        ('Secrets', (970, 800)),
        ],
    },
]

URL_OVERRIDES = {
    'Databricks': 'https://apis.apis.io/apis/databricks/databricks/',
    'Clusters': 'https://apis.apis.io/apis/databricks/clusters-api/',
    'Jobs': 'https://apis.apis.io/apis/databricks/jobs-api/',
    'Workspace': 'https://apis.apis.io/apis/databricks/workspace-api/',
    'SQL Warehouses': 'https://apis.apis.io/apis/databricks/sql-warehouses-api/',
    'Pipelines': 'https://apis.apis.io/apis/databricks/pipelines-api/',
    'Serving Endpoints': 'https://apis.apis.io/apis/databricks/serving-endpoints-api/',
    'Secrets': 'https://apis.apis.io/apis/databricks/secrets-api/',
    'Instance Pools': 'https://apis.apis.io/apis/databricks/instance-pools-api/',
    'Token Mgmt': 'https://apis.apis.io/apis/databricks/token-management-api/',
    'Catalogs': 'https://apis.apis.io/apis/databricks/catalogs-api/',
    'Vector Search Idx': 'https://apis.apis.io/apis/databricks/vector-search-indexes-api/',
    'Model Versions': 'https://apis.apis.io/apis/databricks/model-versions-api/',
    'Permissions': 'https://apis.apis.io/apis/databricks/permissions-api/',
    'Repos': 'https://apis.apis.io/apis/databricks/repos-api/',
    'Git Creds': 'https://apis.apis.io/apis/databricks/git-credentials-api/',
    'Cluster Policies': 'https://apis.apis.io/apis/databricks/cluster-policies-api/',
    'Libraries': 'https://apis.apis.io/apis/databricks/libraries-api/',
    'Statement Execution': 'https://apis.apis.io/apis/databricks/statement-execution-api/',
    'Queries': 'https://apis.apis.io/apis/databricks/queries-api/',
    'Alerts': 'https://apis.apis.io/apis/databricks/alerts-api/',
    'Schemas': 'https://apis.apis.io/apis/databricks/schemas-api/',
    'Tables': 'https://apis.apis.io/apis/databricks/tables-api/',
    'Volumes': 'https://apis.apis.io/apis/databricks/volumes-api/',
    'Functions': 'https://apis.apis.io/apis/databricks/functions-api/',
    'Grants': 'https://apis.apis.io/apis/databricks/grants-api/',
    'External Locations': 'https://apis.apis.io/apis/databricks/external-locations-api/',
    'Storage Credentials': 'https://apis.apis.io/apis/databricks/storage-credentials-api/',
    'Metastores': 'https://apis.apis.io/apis/databricks/metastores-api/',
    'Connections': 'https://apis.apis.io/apis/databricks/connections-api/',
    'Vector Search Endpts': 'https://apis.apis.io/apis/databricks/vector-search-endpoints-api/',
    'Apps': 'https://apis.apis.io/apis/databricks/apps-api/',
    'Files': 'https://apis.apis.io/apis/databricks/files-api/',
    'Tokens': 'https://apis.apis.io/apis/databricks/tokens-api/',
    'Groups': 'https://apis.apis.io/apis/databricks/groups-api/',
    'Current User': 'https://apis.apis.io/apis/databricks/current-user-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Databricks API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: databricks/openapi · github.com/api-evangelist/databricks',
        out_dir=Path(__file__).resolve().parent,
        out_basename='databricks-subway-map',
        provider_id='databricks',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
